### ISSUE TITLE
你的数据库的脚本呢？哥们

### ISSUE THREAD

**Issue by YuHangZM** [guduyt/SSM#2]

**Comment by wqxcloud** [comment]
您好，可以提供下数据库脚本吗？ 还是说不需要数据库脚本？

**Comment by wqxcloud** [comment]
是不需要数据库文件吗，怎么运行，git主可以方便说下嘛，想学习下，感谢

**Comment by guduyt** [comment]
在项目的目录SSM/src/main/resources/env/dev.properties文件有数据库账号密码，你可以直接连接MySQL数据库查看脚本

**Comment by wqxcloud** [comment]
博主，直接连接数据库 有ip吗？ 服务器ip是多少 哈
